version: '3'
services:
  dns:
    container_name: dns
    build:
      context: .
      dockerfile: dns/Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - STREAM_IP=10.33.71.1
      - UPSTREAM_DNS=192.168.99.1
  nginx:
    container_name: nginx
    image: ghcr.io/technotut/sonycam-nginx:main
    ports:
      - "10080:80"
      - "1935:1935"