services:
  dns:
    container_name: dns
    build: ./dns
    ports:
      - "53:53/udp"
      - "53:53"
  nginx:
    container_name: nginx
    image: ghcr.io/technotut/sonycam-nginx:main
    ports:
      - "8080:80"
      - "1935:1935"
    environment:
      - SERVER_URL=rtmp://10.33.0.1:1935/live/test